### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by claire0613**
Hi Teacher,
I already pushed the new code on the Github.
If you find some wrong, please let me know.
thanks

姓名梁庭瑜 
http://18.210.40.247:3000/
http://18.210.40.247:3000/attraction/2

### CODE REVIEW

**Comment by cwpeng** [comment]
Aspect ratio (長寬比) of images should keep the same as original ones in any devices. Fix issue and leave comment for me to review again.

未命名-2

**Comment by claire0613** [comment]
I pushed the codes again!
Could you help me to confirm the website?

**Comment by claire0613** [comment]
I pushed the codes again!
Could teacher help me to check, please?

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
