### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by claire0613**
http://18.210.40.247:3000/api/attractions?page=0
http://18.210.40.247:3000/api/attractions?page=0&keyword=溫泉
http://18.210.40.247:3000/api/attraction/2
梁庭瑜 discord: claire0711

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
"nextPage" of http://18.210.40.247:3000/api/attractions?page=4 and http://18.210.40.247:3000/api/attractions?page=0&keyword=%E6%BA%AB%E6%B3%89 should be null, because there is no next page of data.

Fix issue, create new commits and ask me to review again.

**Comment by claire0613** [comment]
已修正完畢 再請老師幫忙檢查 感謝

**Comment by cwpeng** [comment]
Try to ask me to review again from right side of this page.

**Review by cwpeng — APPROVED** [review]
OK. Well Done.

Suggestion: use second arguments in mycursor.execute() method to apply variable data in SQL query. It can help prevent SQL Injection attack.

**Pull request merged**
